name: Compile LVGL to .mpy for RP2040

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi
        pip install pyelftools

    - name: Clone LVGL
      run: |
        git clone https://github.com/lvgl/lvgl.git
        cd lvgl
        mv lv_conf_template.h lv_conf.h
        sed -i 's/#if 0/#if 1/' lv_conf.h

    - name: Clone MicroPython
      run: |
        git clone https://github.com/micropython/micropython.git
        cd micropython
        git submodule update --init

    - name: Compile LVGL .c files to .o files for RP2040
      run: |
        cd lvgl/src
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_group.o core/lv_group.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj.o core/lv_obj.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_class.o core/lv_obj_class.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_draw.o core/lv_obj_draw.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_event.o core/lv_obj_event.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_id_builtin.o core/lv_obj_id_builtin.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_pos.o core/lv_obj_pos.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_property.o core/lv_obj_property.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_scroll.o core/lv_obj_scroll.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_style.o core/lv_obj_style.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_style_gen.o core/lv_obj_style_gen.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_obj_tree.o core/lv_obj_tree.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -DLV_CONF_INCLUDE_SIMPLE -c -o core/lv_refr.o core/lv_refr.c

    - name: Create .mpy file from .o files
      run: |
        python3 /home/runner/work/micropython/tools/mpy_ld.py lvgl.mpy \
        core/lv_group.o \
        core/lv_obj.o \
        core/lv_obj_class.o \
        core/lv_obj_draw.o \
        core/lv_obj_event.o \
        core/lv_obj_id_builtin.o \
        core/lv_obj_pos.o \
        core/lv_obj_property.o \
        core/lv_obj_scroll.o \
        core/lv_obj_style.o \
        core/lv_obj_style_gen.o \
        core/lv_obj_tree.o \
        core/lv_refr.o

    - name: Upload compiled .mpy
      uses: actions/upload-artifact@v3
      with:
        name: lvgl.mpy
        path: lvgl/src/lvgl.mpy
