name: rp2 port

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        board: [PICO]
    steps:
    - name: lv_micro
      run: git clone https://github.com/lvgl/lv_micropython.git
      
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1.3.0
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    
    - name: Initialize lv_bindings submodule
      run: |
        cd lv_micropython
        git submodule update --init --recursive lib/lv_bindings
      
    - name: Initialize Micropython submodules
      run: |
        cd lv_micropython
        make -C ports/rp2 BOARD=${{ matrix.board }} USER_C_MODULES=../../lib/lv_bindings/bindings.cmake submodules
    
    - name: Build mpy-cross
      run: |
        cd lv_micropython
        make -j $(nproc) -C mpy-cross
    
    - name: Build ${{ matrix.board }}
      run: |
        cd lv_micropython
        make -j $(nproc) -C ports/rp2 BOARD=${{ matrix.board }} USER_C_MODULES=../../lib/lv_bindings/bindings.cmake

    - name: Clonar el SDK de Raspberry Pi Pico
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init lib/mbedtls
        cd ..

    - name: Clonar picotool
      run: |
        git clone https://github.com/raspberrypi/picotool.git
        cd picotool
        mkdir build
        cd build
        export PICO_SDK_PATH=../../pico-sdk  # Asegúrate de que esta ruta sea correcta
        cmake ..
        make
        cd ../..

    - name: Convertir .elf a .uf2
      run: |
        ./picotool/build/picotool uf2 convert ../lv_micropython/ports/rp2/build-${{ matrix.board }}/firmware.elf ../lv_micropython/ports/rp2/build-${{ matrix.board }}/firmware.uf2
      
      #  ./pico-sdk/build/elf2uf2 ../lv_micropython/ports/rp2/build-${{ matrix.board }}/firmware.elf ../lv_micropython/ports/rp2/build-${{ matrix.board }}/firmware.uf2
    
    - uses: actions/upload-artifact@v3
      if: ${{ env.GITHUB_EVENT_NAME }} == 'push'
      with:
        name: ${{ matrix.board }}.uf2
        path: lv_micropython/ports/rp2/build-${{ matrix.board }}/firmware.uf2
