name: LVGL, RP2040, and ESP32 S3 N16R8 builds

permissions:
  contents: write

on:
  push:
    tags:
     - 'v*'
  schedule:
     - cron: '0 0 * * 0'  # Se ejecutar치 a las 00:00 UTC cada domingo
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Clone lv_micropython
      run: git clone --recurse-submodules https://github.com/lvgl/lv_micropython.git

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y build-essential git wget flex bison gperf pkg-config python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: Clone ESP-IDF
      run: |
        mkdir -p esp
        cd esp
        git clone -b v5.2.2 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf/tools
        python3 idf_tools.py install cmake
        cd ..
        ./install.sh esp32s3
        cd

    # Pasos para la compilaci칩n de RP2040
    - name: Set up RP2040 toolchain
      run: |
        cd lv_micropython
        tools/ci.sh setup-rp2040-toolchain

    - name: Compile RP2040
      run: |
        cd lv_micropython
        make -j$(nproc) -C ports/rp2 BOARD=PICO

    - name: Move RP2040 binaries
      run: |
        mkdir -p ./artifacts
        cp lv_micropython/ports/rp2/build-PICO/firmware.uf2 ./artifacts/rp2040_firmware.uf2 || true

    # Integraci칩n de compilaci칩n ESP32S3
    - name: Clone repo smartconfig by Walkline80
      run: git clone https://gitee.com/walkline/micropython-smartconfig-cmodule.git smartconfig

    - name: Clone Micropython for ESP32S3
      run: git clone --recurse-submodules https://github.com/micropython/micropython.git
      
    - name: Copy board config
      run: cp -r ESP32_GENERIC_S3_N16R8 micropython/ports/esp32/boards/

    - name: Compile ESP32 S3 with SmartConfig
      continue-on-error: true
      run: |
        source esp/esp-idf/export.sh
        cd micropython/
        make -C mpy-cross
        export IDF_TARGET=esp32s3
        cd ports/esp32/
        idf.py -D MICROPY_BOARD=ESP32_GENERIC_S3_N16R8 \
               -D MICROPY_BOARD_DIR="$GITHUB_WORKSPACE/micropython/ports/esp32/boards/ESP32_GENERIC_S3_N16R8" \
               -D USER_C_MODULES="$GITHUB_WORKSPACE/smartconfig/cmodules/micropython.cmake" -B build-ESP32_GENERIC_S3_N16R8 build

    - name: Move binaries ESP32 S3 with SmartConfig
      if: success() || failure()
      run: |
        mkdir -p ./artifacts
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/micropython.bin ./artifacts/micropython_smart.bin || true
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/bootloader/bootloader.bin ./artifacts/bootloader_smart.bin || true
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8/partition_table/partition-table.bin ./artifacts/partition-table_smart.bin || true

    - name: Compile ESP32 S3 without SmartConfig
      continue-on-error: true
      run: |
        source esp/esp-idf/export.sh
        cd micropython/
        make -C mpy-cross
        export IDF_TARGET=esp32s3
        cd ports/esp32/
        idf.py -D MICROPY_BOARD=ESP32_GENERIC_S3_N16R8 \
               -D MICROPY_BOARD_DIR="$GITHUB_WORKSPACE/micropython/ports/esp32/boards/ESP32_GENERIC_S3_N16R8" \
               -B build-ESP32_GENERIC_S3_N16R8_no_smart build

    - name: Move binaries ESP32 S3 without SmartConfig
      if: success() || failure()
      run: |
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8_no_smart/micropython.bin ./artifacts/micropython.bin || true
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8_no_smart/bootloader/bootloader.bin ./artifacts/bootloader.bin || true
        cp micropython/ports/esp32/build-ESP32_GENERIC_S3_N16R8_no_smart/partition_table/partition-table.bin ./artifacts/partition-table.bin || true

    - name: Generate Tag
      id: tag
      run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ env.TAG_NAME }}
        title: "Release for version ${{ env.TAG_NAME }}"
        files: ./artifacts/*
