name: Compile LVGL to .mpy for RP2040

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi
        pip install pyelftools

    - name: Clone LVGL
      run: |
        git clone https://github.com/lvgl/lvgl.git
        cd lvgl

    - name: Clone MicroPython
      run: |
        git clone https://github.com/micropython/micropython.git
        cd micropython
        git submodule update --init

    - name: Compile LVGL .c files to .o files for RP2040
      run: |
        cd lvgl/src
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -o core/lv_core.o core/lv_core.c
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -c -o draw/lv_draw.o draw/lv_draw.c
        # Agrega aquí otros archivos .c que necesites compilar

    - name: Create .mpy file from .o files
      run: |
        python3 /home/runner/work/micropython/tools/mpy_ld.py lvgl.mpy core/lv_core.o draw/lv_draw.o
        # Asegúrate de incluir todos los .o necesarios

    - name: Upload compiled .mpy
      uses: actions/upload-artifact@v3
      with:
        name: lvgl.mpy
        path: lvgl/src/lvgl.mpy
