name: Build ESP32-C3 MicroPython

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-esp32-c3:
    runs-on: ubuntu-latest
    env:
      IDF_CCACHE_ENABLE: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
      
      - name: Clone MicroPython
        run: |
          git clone --depth 1 https://github.com/micropython/micropython.git
       
      - id: idf_ver
        name: Read ESP-IDF and Python version from tools/ci.sh
        run: |
          source micropython/tools/ci.sh
          echo "IDF_VER=${IDF_VER}" | tee -a "$GITHUB_OUTPUT"
          echo "PYTHON_VER=${PYTHON_VER}" | tee -a "$GITHUB_OUTPUT"
      
      - name: Setup Python from ci.sh
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ steps.idf_ver.outputs.PYTHON_VER }}

      - name: Cache pip dependencies
        uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('micropython/tools/ci.sh') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git coreutils wget make cmake ninja-build ccache gcc g++ python3-pip python3-setuptools python3-venv
          pip3 install --upgrade pip
          pip3 install pyelftools ar
          mkdir -p ~/.ccache
          echo "max_size = 500M" > ~/.ccache/ccache.conf
          echo "cache_dir = $HOME/.ccache" >> ~/.ccache/ccache.conf
          ccache -s

      - name: Cache esp-idf
        id: cache-idf
        uses: actions/cache@v4.2.3
        with:
          path: esp-idf
          key: esp-idf-${{ steps.idf_ver.outputs.IDF_VER }}-${{ hashFiles('micropython/tools/ci.sh') }}
          restore-keys: |
            esp-idf-
                   
      - name: Setup ESP-IDF
        env:
          IDF_VER: ${{ steps.idf_ver.outputs.IDF_VER }}
        if: steps.cache-idf.outputs.cache-hit != 'true'
        run: |
          rm -rf esp-idf
          git clone --depth 1 --branch $IDF_VER https://github.com/espressif/esp-idf.git
          git -C esp-idf submodule update --init --recursive --filter=tree:0
          ./esp-idf/install.sh

      - name: Export ESP-IDF environment
        #shell: bash
        #env:
         # PATH: /usr/bin:/bin:${{ env.PATH }}
        run: |
          source esp-idf/export.sh
          echo "IDF_PATH=$GITHUB_WORKSPACE/esp-idf" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          idf.py --version
          #if ! source esp-idf/export.sh > /dev/null 2>&1; then
           # echo "Entorno virtual no encontrado, reinstalando..."
            #./esp-idf/install.sh
          #fi
          #echo "PATH before source: $PATH"
          #source esp-idf/export.sh
          #echo "export CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          #ccache -s
          #env

      - name: Cache ccache
        id: cache-ccache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/tools/ci.sh') }}-${{ steps.idf_ver.outputs.IDF_VER }}

      - name: Build mpy-cross and ESP32-C3 port
        shell: bash
        #env:
        #  IDF_PATH: ${{ github.workspace }}/esp-idf
        #  PATH: ${{ github.workspace }}/esp-idf/tools:/usr/bin:/bin:${{ env.PATH }}
        run: |
          source esp-idf/export.sh
          export IDF_TARGET=esp32c3
          #export CCACHE_DIR="$HOME/.ccache"
          cd ${{ github.workspace }}/micropython
          make -j$(nproc) -C mpy-cross
          make -j$(nproc) -C ports/esp32 submodules
          make -j$(nproc) -C ports/esp32 BOARD=ESP32_GENERIC_C3
          ccache -s

      - name: Verify build artifacts
        run: |
          ls -lh micropython/ports/esp32/build-ESP32_GENERIC_C3/*.bin

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: esp32c3-firmware
          path: |
            micropython/ports/esp32/build-ESP32_GENERIC_C3/firmware.bin
            micropython/ports/esp32/build-ESP32_GENERIC_C3/micropython.bin

